// Package apimanagerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230506011706-29ebe3262399 DO NOT EDIT.
package apimanagerevents

import (
	"time"

	"github.com/Pickausernaame/chat-service/internal/types"
)

// Defines values for BaseEventEventType.
const (
	BaseEventEventTypeNewChatEvent    BaseEventEventType = "NewChatEvent"
	BaseEventEventTypeNewMessageEvent BaseEventEventType = "NewMessageEvent"
)

// Defines values for NewChatEventEventType.
const (
	NewChatEventEventTypeNewChatEvent    NewChatEventEventType = "NewChatEvent"
	NewChatEventEventTypeNewMessageEvent NewChatEventEventType = "NewMessageEvent"
)

// Defines values for NewMessageEventEventType.
const (
	NewMessageEventEventTypeNewChatEvent    NewMessageEventEventType = "NewChatEvent"
	NewMessageEventEventTypeNewMessageEvent NewMessageEventEventType = "NewMessageEvent"
)

// BaseEvent defines model for BaseEvent.
type BaseEvent struct {
	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType BaseEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// BaseEventEventType Type of the event
type BaseEventEventType string

// MessageId defines model for MessageId.
type MessageId struct {
	MessageId types.MessageID `json:"messageId"`
}

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// ClientId Unique identifier for the client
	ClientId types.UserID `json:"clientId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewChatEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewChatEventEventType Type of the event
type NewChatEventEventType string

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	// AuthorId Unique identifier for the author
	AuthorId types.UserID `json:"authorId"`

	// Body Body of the message
	Body string `json:"body"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// CreatedAt Date and time of event creation
	CreatedAt time.Time `json:"createdAt"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewMessageEventEventType `json:"eventType"`
	MessageId types.MessageID          `json:"messageId"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewMessageEventEventType Type of the event
type NewMessageEventEventType string
