// Code generated by options-gen. DO NOT EDIT.
package managerv1

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	canReceiveProblemsUseCase canReceiveProblemsUseCase,
	setReadyReceiveProblemsUseCase setReadyReceiveProblemsUseCase,
	getAssignedProblemsUseCase getAssignedProblemsUseCase,
	getChatHistoryUseCase getChatHistoryUseCase,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.canReceiveProblemsUseCase = canReceiveProblemsUseCase
	o.setReadyReceiveProblemsUseCase = setReadyReceiveProblemsUseCase
	o.getAssignedProblemsUseCase = getAssignedProblemsUseCase
	o.getChatHistoryUseCase = getChatHistoryUseCase

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("canReceiveProblemsUseCase", _validate_Options_canReceiveProblemsUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("setReadyReceiveProblemsUseCase", _validate_Options_setReadyReceiveProblemsUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("getAssignedProblemsUseCase", _validate_Options_getAssignedProblemsUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("getChatHistoryUseCase", _validate_Options_getChatHistoryUseCase(o)))
	return errs.AsError()
}

func _validate_Options_canReceiveProblemsUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.canReceiveProblemsUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `canReceiveProblemsUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_setReadyReceiveProblemsUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.setReadyReceiveProblemsUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `setReadyReceiveProblemsUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_getAssignedProblemsUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.getAssignedProblemsUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `getAssignedProblemsUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_getChatHistoryUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.getChatHistoryUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `getChatHistoryUseCase` did not pass the test: %w", err)
	}
	return nil
}
