version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: chat-service
      POSTGRES_USER: chat-service
      POSTGRES_PASSWORD: chat-service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  postgresql-data:
