// Code generated by options-gen. DO NOT EDIT.
package logger

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptLogLevelOptionSetter func(o *LogLevelOption)

func NewLogLevelOption(
	value string,
	options ...OptLogLevelOptionSetter,
) LogLevelOption {
	o := LogLevelOption{}

	// Setting defaults from field tag (if present)

	o.value = value

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *LogLevelOption) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("value", _validate_LogLevelOption_value(o)))
	return errs.AsError()
}

func _validate_LogLevelOption_value(o *LogLevelOption) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.value, "required,oneof=debug info warn error"); err != nil {
		return fmt461e464ebed9.Errorf("field `value` did not pass the test: %w", err)
	}
	return nil
}
