[global]
env = "dev"
ver = "0.0.1"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"
[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "FOts8F0QQpGIVMwOX8788n5Z1l10aSje"
debug_mode = true
[clients.psql]
host = "localhost:5433"
user_name = "chat-service"
password = "chat-service"
db_name = "chat-service"
debug = true

[services]
[services.manager_load]
max_problems_at_same_time = 5

[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "73367639792442264529482B4D625165"

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[services.afc_verdicts_processor]
brokers = ["localhost:9092"]
consumers = 4
consumer_group = "chat-service_afc-verdict-processor"
verdicts_topic = "afc.msg-verdicts"
dlq_topic = "dql.msg-verdicts"
verdicts_signing_public_key = """
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgEmpZJXuAn7fTOrEyxCaa5NBKWd+
KMFmLaPmTc5nAeP8AL+wgcVffLtAm/ouA9DP+HN0sl+01subAz+r5AvXrIoALGk/
ltXOwIT9DdAe+8HhRZyAhpKUqkwI0TS1RK54lDg0v5QQJD2c+4cUA0umAhD53Qc9
KPiLEpexQ09tQaa1AgMBAAE=
-----END PUBLIC KEY-----
"""


[sentry]
dsn = "http://7dc894a2773a424780da7a0464bd3241@127.0.0.1:9000/2"

