[global]
env = "dev"
ver = "0.0.1"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "FOts8F0QQpGIVMwOX8788n5Z1l10aSje"
debug_mode = true
[clients.psql]
host = "localhost:5433"
user_name = "chat-service"
password = "chat-service"
db_name = "chat-service"
debug = false

[sentry]
dsn = "http://7dc894a2773a424780da7a0464bd3241@127.0.0.1:9000/2"
