// Code generated by options-gen. DO NOT EDIT.
package config

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptDebugServerConfigSetter func(o *DebugServerConfig)

func NewDebugServerConfig(
	options ...OptDebugServerConfigSetter,
) DebugServerConfig {
	o := DebugServerConfig{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithAddr(opt string) OptDebugServerConfigSetter {
	return func(o *DebugServerConfig) {
		o.Addr = opt
	}
}

func (o *DebugServerConfig) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("Addr", _validate_DebugServerConfig_Addr(o)))
	return errs.AsError()
}

func _validate_DebugServerConfig_Addr(o *DebugServerConfig) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `Addr` did not pass the test: %w", err)
	}
	return nil
}
