// Code generated by options-gen. DO NOT EDIT.
package config

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptGlobalConfigSetter func(o *GlobalConfig)

func NewGlobalConfig(
	options ...OptGlobalConfigSetter,
) GlobalConfig {
	o := GlobalConfig{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithEnv(opt string) OptGlobalConfigSetter {
	return func(o *GlobalConfig) {
		o.Env = opt
	}
}

func (o *GlobalConfig) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("Env", _validate_GlobalConfig_Env(o)))
	return errs.AsError()
}

func _validate_GlobalConfig_Env(o *GlobalConfig) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Env, "required,oneof=dev stage prod"); err != nil {
		return fmt461e464ebed9.Errorf("field `Env` did not pass the test: %w", err)
	}
	return nil
}
