// Code generated by options-gen. DO NOT EDIT.
package config

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptLogConfigSetter func(o *LogConfig)

func NewLogConfig(
	options ...OptLogConfigSetter,
) LogConfig {
	o := LogConfig{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLevel(opt string) OptLogConfigSetter {
	return func(o *LogConfig) {
		o.Level = opt
	}
}

func (o *LogConfig) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("Level", _validate_LogConfig_Level(o)))
	return errs.AsError()
}

func _validate_LogConfig_Level(o *LogConfig) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.Level, "required,oneof=debug info warn error"); err != nil {
		return fmt461e464ebed9.Errorf("field `Level` did not pass the test: %w", err)
	}
	return nil
}
