// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230506011706-29ebe3262399 DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/Pickausernaame/chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BaseEventEventType.
const (
	BaseEventEventTypeNewChatEvent BaseEventEventType = "NewChatEvent"
)

// Defines values for NewChatEventEventType.
const (
	NewChatEventEventTypeNewChatEvent NewChatEventEventType = "NewChatEvent"
)

// BaseEvent defines model for BaseEvent.
type BaseEvent struct {
	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType BaseEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// BaseEventEventType Type of the event
type BaseEventEventType string

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// ClientId Unique identifier for the client
	ClientId types.UserID `json:"clientId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewChatEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewChatEventEventType Type of the event
type NewChatEventEventType string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yTP2/bMBDFvwpx7UhbDroEHJN08NA2aJMp8EBTJ4s1/+VI2S0MffeClOJ/7WID6WT6",
	"qCPfe/fjDpS3wTt0KYLYQVQtWlmWdzLi5w26lP8E8gEpaSxbmMvzOi9rjIp0SNo7EPDs9GuHTNfokm40",
	"Ems8sdQiKy3AofFkZQIBXadr4JB+BwQBMZF2K+Dwa7Lyk7GYf+K0aJg/HO9NtA2eBmEytSBgpVPbLafK",
	"2+pRq7XsIpKT0mKlWpkmEWmjFVbapVw3VTka+p4PXp7KheducpX55kQ/us6CeIGvuL1vZRoCWpz76DkQ",
	"vnYYL0xpbLoqp+/jhe+U1GhJE9bZ/xsCxwEem170/DQjsQNpzLcGxMsOPhI2IOBDdaCvGtGrDtz1/Bw8",
	"Jd2TXOMXT/hIfmnQxr/jnbtaK5kwMt0wK51cITElHUtyjcx6QhbemvfBLr03KF2eXM7hsrHljqtmluN5",
	"P7SV0Re/06HnKjPPEek/0bd3tp8W/ycbh4fplz9RJegX5SztGp9VJZ1M3r2Tbs1+dCGrZXko7L7cwAqI",
	"GZMNUhyy29xkSHxAJ4MGAZ+mN9MZ8OIwgnCdMRyyEaRYYD+N/gE3aHyw+fThK+DQkQEB2yiqynglTetj",
	"Erez21m1jVnznwAAAP///isPi6cFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
