// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230506011706-29ebe3262399 DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/Pickausernaame/chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BaseEventEventType.
const (
	BaseEventEventTypeChatClosedEvent BaseEventEventType = "ChatClosedEvent"
	BaseEventEventTypeNewChatEvent    BaseEventEventType = "NewChatEvent"
	BaseEventEventTypeNewMessageEvent BaseEventEventType = "NewMessageEvent"
)

// Defines values for ChatClosedEventEventType.
const (
	ChatClosedEventEventTypeChatClosedEvent ChatClosedEventEventType = "ChatClosedEvent"
	ChatClosedEventEventTypeNewChatEvent    ChatClosedEventEventType = "NewChatEvent"
	ChatClosedEventEventTypeNewMessageEvent ChatClosedEventEventType = "NewMessageEvent"
)

// Defines values for NewChatEventEventType.
const (
	NewChatEventEventTypeChatClosedEvent NewChatEventEventType = "ChatClosedEvent"
	NewChatEventEventTypeNewChatEvent    NewChatEventEventType = "NewChatEvent"
	NewChatEventEventTypeNewMessageEvent NewChatEventEventType = "NewMessageEvent"
)

// Defines values for NewMessageEventEventType.
const (
	NewMessageEventEventTypeChatClosedEvent NewMessageEventEventType = "ChatClosedEvent"
	NewMessageEventEventTypeNewChatEvent    NewMessageEventEventType = "NewChatEvent"
	NewMessageEventEventTypeNewMessageEvent NewMessageEventEventType = "NewMessageEvent"
)

// BaseEvent defines model for BaseEvent.
type BaseEvent struct {
	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType BaseEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// BaseEventEventType Type of the event
type BaseEventEventType string

// ChatClosedEvent defines model for ChatClosedEvent.
type ChatClosedEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType ChatClosedEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// ChatClosedEventEventType Type of the event
type ChatClosedEventEventType string

// MessageId defines model for MessageId.
type MessageId struct {
	MessageId types.MessageID `json:"messageId"`
}

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// ClientId Unique identifier for the client
	ClientId types.UserID `json:"clientId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewChatEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewChatEventEventType Type of the event
type NewChatEventEventType string

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	// AuthorId Unique identifier for the author
	AuthorId types.UserID `json:"authorId"`

	// Body Body of the message
	Body string `json:"body"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// CreatedAt Date and time of event creation
	CreatedAt time.Time `json:"createdAt"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewMessageEventEventType `json:"eventType"`
	MessageId types.MessageID          `json:"messageId"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewMessageEventEventType Type of the event
type NewMessageEventEventType string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW/bMAz9KwK3oxKn6KXQbf04FFi7YmtPRQ+MTcda9OFKctIiyH8faDtNmhQDEmDB",
	"MOwUhxIlvsf3TC8g97b2jlyKoBYQ84osto/nGOlqRi7xnzr4mkLS1C4Rh68Lfiwo5kHXSXsHCh6cfm5I",
	"6IJc0qWmIEofRKpItCkgofTBYgIFTaMLkJBeawIFMQXtJiDhZTDxgz7IP3HY1nB9ubk20Lb2oSsMUwUK",
	"JjpVzXiYe5vd6XyKTaTgEC1leYVpECnMdE6ZdonjJmuPhuVSdlju2wu30XBU+PJd/eQaC+oRbml+UWG6",
	"6sO3NL+hGHFCqwivXhgfqegiT9tYlxICPTcU92SyTzqIy+/9hX+IzR6SDlQwRyuZbJK8CfppuUuTWgAa",
	"860E9biAz4FKUPApW4s06xWareW5lNv6zNHd45RufKC74MeGbNxl+NoVOsdEUehSWHQ4oSBydCLhlIT1",
	"gUS9Sn7jduy9IXTcPKZiv85xxkFtY5KO1LMelfyQw7WG/fgn5QmW3MJe+B0X7xthN5f2x706+TjQ18Uy",
	"qncG/6/KI6tSQm703kOmyzkIzEOkcCyLrZDJQ9y2PWkOlObvdq4NvStibFLlw35t6XL+urZIGPvidRfI",
	"uS9eV2O/fyeABIsvX8lN+MbT0WgkwWq3Cpx8MNv/HSMGwkTFl7SL5RITCXSFSNq2X0rtnBdtBu/YAFNg",
	"ogFv20G0bY83hfX92azgjdaPvMEHaVd6rjPpZHj1HN1U/GhqZkMwT+KidZ9oncCv0BmF2KGZnXDffE0O",
	"aw0KTocnwxHIlsEIyjXGSGCiKMTWbVtk0IyMry2f3u0CCU0woGAeVZYZn6OpfEzqbHQ2yuaRa/4VAAD/",
	"/zJmJfWACwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
