// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230506011706-29ebe3262399 DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/Pickausernaame/chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BaseEventEventType.
const (
	BaseEventEventTypeNewChatEvent    BaseEventEventType = "NewChatEvent"
	BaseEventEventTypeNewMessageEvent BaseEventEventType = "NewMessageEvent"
)

// Defines values for ChatClosedEventEventType.
const (
	ChatClosedEventEventTypeNewChatEvent    ChatClosedEventEventType = "NewChatEvent"
	ChatClosedEventEventTypeNewMessageEvent ChatClosedEventEventType = "NewMessageEvent"
)

// Defines values for NewChatEventEventType.
const (
	NewChatEventEventTypeNewChatEvent    NewChatEventEventType = "NewChatEvent"
	NewChatEventEventTypeNewMessageEvent NewChatEventEventType = "NewMessageEvent"
)

// Defines values for NewMessageEventEventType.
const (
	NewMessageEventEventTypeNewChatEvent    NewMessageEventEventType = "NewChatEvent"
	NewMessageEventEventTypeNewMessageEvent NewMessageEventEventType = "NewMessageEvent"
)

// BaseEvent defines model for BaseEvent.
type BaseEvent struct {
	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType BaseEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// BaseEventEventType Type of the event
type BaseEventEventType string

// ChatClosedEvent defines model for ChatClosedEvent.
type ChatClosedEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType ChatClosedEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// ChatClosedEventEventType Type of the event
type ChatClosedEventEventType string

// MessageId defines model for MessageId.
type MessageId struct {
	MessageId types.MessageID `json:"messageId"`
}

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	// CanTakeMoreProblems Indicates if manager can take more problems
	CanTakeMoreProblems bool `json:"canTakeMoreProblems"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// ClientId Unique identifier for the client
	ClientId types.UserID `json:"clientId"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewChatEventEventType `json:"eventType"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewChatEventEventType Type of the event
type NewChatEventEventType string

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	// AuthorId Unique identifier for the author
	AuthorId types.UserID `json:"authorId"`

	// Body Body of the message
	Body string `json:"body"`

	// ChatId Unique identifier for the chat
	ChatId types.ChatID `json:"chatId"`

	// CreatedAt Date and time of event creation
	CreatedAt time.Time `json:"createdAt"`

	// EventId Unique identifier for the event
	EventId types.EventID `json:"eventId"`

	// EventType Type of the event
	EventType NewMessageEventEventType `json:"eventType"`
	MessageId types.MessageID          `json:"messageId"`

	// RequestId Unique identifier for the request
	RequestId types.RequestID `json:"requestId"`
}

// NewMessageEventEventType Type of the event
type NewMessageEventEventType string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW/bMAz9KwK3oxKn6KXwbf04FFi7YmtPRQ+MTcda9OFKctKiyH8fKDsfTYoBCbBg",
	"GHaKQ4kS3+N7pt+gcKZxlmwMkL9BKGoymB7PMdDVjGzkP413DfmoKC0Rh69LfiwpFF41UTkLOTxY9dyS",
	"UCXZqCpFXlTOi1iTSCkgoXLeYIQc2laVICG+NgQ5hOiVnYCEl8HEDfog/4RhquH6cnNtoEzjfFcYxhpy",
	"mKhYt+Nh4Ux2p4optoG8RTSUFTXGQSA/UwVlykaO6ywdDYuF7LDcpwu30XBUuOpd/WRbA/kj3NL8osZ4",
	"1YdvaX5DIeCkp+xpG9lCgqfnlsKevPVJBzH3vb/wD3HXQ1KeSmZkKYpNSjdBPy0kMGUX2gUqV8pCrb9V",
	"kD++wWdPFeTwKVtLMuv1mK3FuJDbaizQ3uOUbpynO+/GmkzYZfjalqrASEGoShi0OCEvCrQi4pSEcZ5E",
	"s0xecTt2ThNabh5TsV/nOOOgtjFJR+pZj0p+yOFaw278k4oIC25hL/OOi/eNMJtL++Nennwc6OtiGdU7",
	"O/9X5ZFVKaHQau+R0uUcBOYhkD+WxZbI5CFu254rB0rzdzvXht4VMbaxdn6/tnQ5f11bJIxd+boL5NyV",
	"r8sh378TQILBl69kJ3zj6Wg0kmCUXQZOPpjt/44RPWGk8kvcxXKJkQTaUkRl0ndRmvMiZfCODTAlRhrw",
	"th1E2/ZYKazvz2YFK1o/8gYfpGzluM6ooubVc7RT8aNtmA3BPImL5D6RnMCv0Bn50KGZnXDfXEMWGwU5",
	"nA5PhiOQicEAuW21lsBEkQ/JbVtk0Iy0awyf3u0CCa3XkMM85FmmXYG6diHmZ6OzUTYPXPOvAAAA///f",
	"g5tEbgsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
